import { jsPDF } from 'jspdf';
import autoTable, { Color } from 'jspdf-autotable';
import { CasualtyReport } from '../types';

export async function generatePDF(report: CasualtyReport) {
  const doc = new jsPDF();
  const primaryColor: [number, number, number] = [185, 28, 28]; // Red-700

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('TEBITA AMBULANCE', 105, 20, { align: 'center' });
  doc.setFontSize(10);
  doc.text('PREHOSPITAL EMERGENCY CARE SYSTEM', 105, 28, { align: 'center' });
  doc.text(`Report ID: ${report.id} | Date: ${report.serviceDate}`, 105, 35, { align: 'center' });

  let y = 50;

  // Section 1: Demography
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('1. DEMOGRAPHY', 15, y);
  y += 5;
  autoTable(doc, {
    startY: y,
    head: [['Field', 'Details']],
    body: [
      ['Patient Name', report.patientName || 'N/A'],
      ['Age / Sex', `${report.age || 'N/A'} / ${report.sex || 'N/A'}`],
      ['Caller Point', report.callerPoint || 'N/A'],
      ['Location', `${report.region || 'N/A'}, ${report.subCity || 'N/A'}`],
      ['Phone', report.phoneNumber || 'N/A']
    ],
    theme: 'striped',
    headStyles: { fillColor: primaryColor }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Section 2: Ambulance & Time
  doc.text('2. AMBULANCE & MISSION TIMELINE', 15, y);
  y += 5;
  autoTable(doc, {
    startY: y,
    body: [
      ['Call Time', report.callTime, 'Departure KM', (report.departureKM || 0).toString()],
      ['Scene Arrival', report.sceneArrivalTime || '--:--', 'Scene KM', (report.sceneArrivalKM || 0).toString()],
      ['Hospital Arrival', report.destinationArrivalTime || '--:--', 'Hospital KM', (report.destinationArrivalKM || 0).toString()],
      ['Return Dispatch', report.returnToDispatchTime || '--:--', 'Return KM', (report.returnKM || 0).toString()],
      ['Ambulance Level', report.ambulanceLevel || 'N/A', 'Vehicle', report.vehicleType || 'N/A']
    ],
    theme: 'grid',
    headStyles: { fillColor: primaryColor }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Primary Survey & Vitals
  doc.text('3. PRIMARY SURVEY & VITALS', 15, y);
  y += 5;
  autoTable(doc, {
    startY: y,
    body: [
      ['Severity', `Category ${report.severity || 'N/A'}`, 'GCS', report.gcs || 'N/A'],
      ['Airway', report.airwayStatus || 'N/A', 'Breathing', report.breathingStatus || 'N/A'],
      ['Circulation', report.circulation || 'N/A', 'Pulse', `${report.peripheralPulse || 'N/A'} (P) / ${report.carotidPulse || 'N/A'} (C)`],
      ['CPR Performed', report.cprPerformed ? 'Yes' : 'No', 'Severe Bleeding', report.severeBleeding ? 'Yes' : 'No']
    ],
    theme: 'striped'
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Generated by Tebita Ambulance System`, 105, 290, { align: 'center' });
  }

  doc.save(`Tebita_Report_${(report.patientName || 'Untitled').replace(/\s/g, '_')}_${report.id.slice(0, 5)}.pdf`);
}